name: aula_inteligente
on:
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2' # Versión de Flutter que ya confirmaste

      # ****** ¡CAMBIO IMPORTANTE AQUÍ! ********
      # Especificamos el directorio de trabajo para este y los siguientes comandos.
      # Asumo que la raíz de tu proyecto Flutter está en la raíz del repositorio clonado.
      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: ./ # Asegura que se ejecuta en la raíz del repositorio

      - name: Build Android APK
        run: flutter build apk --release
        working-directory: ./ # Asegura que se ejecuta en la raíz del repositorio

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5