name: aula_inteligente

on:
  push:
    branches:
      - main # Asegúrate de que esta sea la rama correcta de tu repositorio móvil

jobs:
  build_android: # Renombre el job para mayor claridad (build_android vs build_ios)
    runs-on: ubuntu-latest # ubuntu-latest es adecuado para compilar Android

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          # ******** ¡MUY IMPORTANTE! REEMPLAZA ESTO CON LA VERSIÓN EXACTA DE FLUTTER QUE USAS ********
          # Basado en tu pubspec.yaml, que indica 'sdk: ^3.7.2', Flutter 3.7.2 es una buena elección.
          flutter-version: '3.7.2' # <-- ¡Esta es la versión que pusiste y parece correcta!

      - name: Get Flutter dependencies
        run: flutter pub get # Instala las dependencias de Dart/Flutter de tu pubspec.yaml

      # Opcional: Si tienes pruebas unitarias, puedes descomentar este paso
      # - name: Run Flutter tests
      #   run: flutter test

      - name: Build Android APK
        run: flutter build apk --release # Compila la aplicación para Android en modo release

      - name: Upload Android APK
        uses: actions/upload-artifact@v4 # Sube el APK generado como un artefacto de la ejecución
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk # Ruta estándar donde Flutter genera el APK
          retention-days: 5 # Días que se guarda el artefacto (puedes ajustar este valor)