name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2' # Reconfirma que esta es la versión que deseas

      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: ./ # <--- ASEGÚRATE QUE ESTA LÍNEA ESTÁ AHÍ Y CORRECTAMENTE INDENTADA

      - name: Build Android APK
        run: flutter build apk --release
        working-directory: ./ # <--- ASEGÚRATE QUE ESTA LÍNEA ESTÁ AHÍ Y CORRECTAMENTE INDENTADA

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5